---
theme: aglaus
baseurl: http://cosmgames.com/
languageCode: en-us
title: Cosm Games

Params:
  Author: "Cosm Games"
  # Birth: "Sun, Feb 26, 1989"
  DateForm: "Mon, Jan 2, 2006"
  # GoogleAnalyticsUserID: "Your ID."
  # GravatarHash: "Your Hash."
  # Facebook: "Your ID."
  # Twitter: "Your ID."
  # Github: "Your ID."
  ShowRelatedPost: True
  # Disqus: "Your Disqus."
  SyntaxHighlightTheme: "solarized_dark.min.css"

# Indexes:
#   tag: "tags"
#
# permalinks:
#   post: /blog/:year/:month/:day/:title/
...
