---
theme: cosmgames.com
baseurl: http://cosmgames.com/
languageCode: en-us
title: Cosm Games
params:
  description: Cosssssmmmmm Games!
  menu:
    - title: About
      url: /page/about/
  footer_links:
    Cosm:
      - title: Cosm Games
        url: /
      - title: About
        url: /page/about/
      - title: Contact
        url: mailto:hello@cosmgames.com
      - title: Blog
        url: http://blog.cosmgames.com/
      - title: Twitter
        url: https://twitter.com/CosmGames
    Scaredy Geek:
      - title: Scaredy Geek
        url: http://scaredygeek.com/
      - title: Twitter
        url: https://twitter.com/ScaredyGeek
  contact:
    - title: Blog
      icon: book
      url: //blog.cosmgames.com/
    - title: Twitter
      icon: twitter
      url: https://twitter.com/CosmGames
    - title: Email
      icon: envelope
      url: mailto:hello@cosmgames.com
...
