---
theme: cosmgames.com
baseurl: http://cosmgames.com/
languageCode: en-us
title: Cosm Games
params:
  description: Cosssssmmmmm Games!
  contact:
    - title: Blog
      icon: book
      url: //blog.cosmgames.com/
    - title: Twitter
      icon: twitter
      url: https://twitter.com/CosmGames
    - title: Email
      icon: envelope
      url: mailto:hello@cosmgames.com
...
